version: "3"
services:
  app:
    container_name: stencil_app
    build:
      context: .
      target: dev
    restart: unless-stopped
    ports:
      - '3333:3333'
    env_file: .env
    volumes: 
      - ./:/usr/src/app
    depends_on:
      - db
  db:
    container_name: stencil_db
    image: postgres:11.2-alpine
    env_file: .env
    ports:
      - '5433:5433'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data