version: '2'

tasks:
  build_dev:
    desc: Builds a dev docker image from the current state of the app
    cmd: docker build -t lapiqure/stencil.dev:latest .
  start:
    desc: Starts the local development docker container on http://localhost:3333
    cmds:
      - docker compose up -d
      # - docker run -p 3333:3333 lapiqure/stencil.dev:latest
  stop_dev:
    desc: Stops the local development docker container
    cmd: docker stop lapiqure/stencil.dev:latest